In [2]:
import requests

url = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+distinct(pl_name)+from+ps+order+by+pl_name+desc+&format=csv"
response = requests.get(url)

# The response will be in CSV format, so you can use the `csv` library to parse it
import csv
reader = csv.reader(response.text.splitlines())
for row in reader:
    print(row)
    
    
#Obtengo la constelacion que pertenecen

['pl_name']
['xi Aql b']
['ups Leo b']
['ups And d']
['ups And c']
['ups And b']
['tau Gem b']
['tau Cet h']
['tau Cet g']
['tau Cet f']
['tau Cet e']
['tau Boo b']
['rho CrB e']
['rho CrB d']
['rho CrB c']
['rho CrB b']
['psi1 Dra B b']
['pi Men d']
['pi Men c']
['omi UMa b']
['omi CrB b']
['ome Ser b']
['nu Oph c']
['nu Oph b']
['nu Oct A b']
['mu2 Sco b']
['mu Leo b']
['kap CrB b']
['kap And b']
['iot Dra c']
['iot Dra b']
['gam1 Leo b']
['gam Psc b']
['gam Lib c']
['gam Lib b']
['gam Cep b']
['eps Tau b']
['eps Ind A b']
['eps Eri b']
['eps CrB b']
['bet UMi b']
['bet Pic c']
['bet Pic b']
['bet Cnc b']
['b Cen AB b']
['alf Tau b']
['alf Ari b']
['YZ Cet d']
['YZ Cet c']
['YZ Cet b']
['YSES 2 b']
['XO-7 b']
['XO-6 b']
['XO-5 b']
['XO-4 b']
['XO-3 b']
['XO-2 S c']
['XO-2 S b']
['XO-2 N b']
['XO-1 b']
['Wolf 503 b']
['Wolf 327 b']
['Wolf 1069 b']
['Wolf 1061 d']
['Wolf 1061 c']
['Wolf 1061 b']
['Wendelstein-2 b']
['Wendelstein-1 b']
['WTS-2 b']
['WTS-1 b']
['WISEP J121756.91+162640.2

In [9]:
import requests
import urllib.parse
import csv
from math import cos, sin,radians

class FetchPlanetsError(Exception):
    pass

def fetch_name_planets(system_solar):
    encoded_system_solar = urllib.parse.quote_plus(system_solar)
    api_url = f"https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+distinct(pl_name),sy_dist,ra,dec+from+ps+where+pl_name+like+%27%25{encoded_system_solar}%25%27+order+by+pl_name+desc&format=csv"
    headers = {
        'User-Agent': 'App'
    }
    response = requests.get(api_url, headers=headers)


    response_data = list(csv.reader(response.text.splitlines()))
    
    if not response_data or len(response_data) == 1:  
        raise FetchPlanetsError("Error 404: No data found for the specified system solar")
    
    return response_data

# Ejemplo de uso
sistema_solar = '14 Her'
try:
    planets_csv = fetch_name_planets(sistema_solar)[1:]
    print(planets_csv)

except FetchPlanetsError as e:
    print(e)


[['14 Her b', '17.9323000', '242.6021014', '43.8163621']]


In [3]:
import requests
import urllib.parse
import csv


def fetch_stellar_hosts():
    api_url = 'https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+distinct(sy_name)+from+stellarhosts&format=csv'
    headers = {
        'User-Agent': 'App'
    }
    response = requests.get(api_url, headers=headers)
    if response.status_code == 404:
        raise FetchPlanetsError("Error 404: Resource not found")
    
    response_data = list(csv.reader(response.text.splitlines()))
    
    return response_data[1:]


print(fetch_stellar_hosts())





[['alf Cen'], ['Kepler-1997'], ['Kepler-540'], ['Kepler-1152'], ['Kepler-1616'], ['Kepler-967'], ['Kepler-129'], ['Kepler-841'], ['HD 66428'], ['HD 4203'], ['Kepler-1785'], ['Kepler-1705'], ['HD 73526'], ['Kepler-1100'], ['K2-153'], ['Kepler-1396'], ['Kepler-765'], ['GJ 422'], ['Kepler-1416'], ['Kepler-1043'], ['Kepler-1886'], ['Kepler-154'], ['Kepler-407'], ['KIC 3558849'], ['HD 62364'], ['GJ 15'], ['Kepler-879'], ['Kepler-1159'], ['Kepler-704'], ['Kepler-452'], ['Kepler-1854'], ['HD 207496'], ['Kepler-542'], ['Kepler-1167'], ['Kepler-1602'], ['OGLE-2018-BLG-1647L'], ['TOI-763'], ['K2-118'], ['Kepler-1351'], ['Kepler-934'], ['Kepler-107'], ['Kepler-1664'], ['Kepler-214'], ['Kepler-551'], ['Kepler-140'], ['Kepler-1569'], ['Kepler-870'], ['Kepler-1761'], ['Kepler-372'], ['Kepler-941'], ['Kepler-1133'], ['HIP 13642 A'], ['Kepler-196'], ['HD 15906'], ['K2-189'], ['HD 22532'], ['HD 106906'], ['Kepler-228'], ['Kepler-946'], ['Kepler-1607'], ['Kepler-135'], ['Kepler-414'], ['51 Eri'], ['TOI-

In [20]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from io import BytesIO
from PIL import Image
import numpy as np

# URL de la página web que contiene las texturas
url = "https://www.solarsystemscope.com/textures/"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Encuentra todos los enlaces de descarga de texturas
    textures = soup.find_all('a', class_='btn-type-1-blue texture-download-button')
    
    # Imprime la información de las texturas
    for texture in textures:
        download_link = texture['href']
        if '2k' in download_link:
            # Construye la URL completa concatenando la parte final de la URL con la URL base de la página
            full_download_link = urljoin(url, download_link)
            # Descarga la imagen desde el enlace completo
            image_response = requests.get(full_download_link)
            if image_response.status_code == 200:
                # Cargar la imagen desde el contenido de la respuesta
                image = Image.open(BytesIO(image_response.content))
                # Convertir la imagen a una matriz numpy
                image_array = np.array(image)
                # Ahora puedes trabajar con image_array
                print(f"Dimensiones de la imagen: {image_array.shape}")
                # Por ejemplo, imprimir los primeros 5 píxeles de la imagen
                print("Primeros 5 píxeles de la imagen:")
                print(image_array[:5])
            else:
                print(f"Error al descargar imagen desde {full_download_link}, estado: {image_response.status_code}")

else:
    print(f"Failed to retrieve the page, status code: {response.status_code}")


Download Link: https://www.solarsystemscope.com/textures/download/2k_mercury.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_venus_surface.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_venus_atmosphere.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_mars.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_jupiter.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_saturn.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_saturn_ring_alpha.png
Download Link: https://www.solarsystemscope.com/textures/download/2k_uranus.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_neptune.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_earth_daymap.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_earth_nightmap.jpg
Download Link: https://www.solarsystemscope.com/textures/download/2k_earth_cl

In [15]:
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from io import BytesIO
from PIL import Image
import numpy as np
def extract_planet_name(filename):
    match = re.search(r'2k_(.+)\.jpg', filename)
    if match:
        return match.group(1)
    return None

def fetch_textures_planets(planet_id):
    url = "https://www.solarsystemscope.com/textures/"
    headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        textures = soup.find_all('a', class_='btn-type-1-blue texture-download-button')

        for texture in textures:
            download_link = texture['href']
            if '2k' in download_link:
                name_planet = extract_planet_name(download_link)
                if name_planet == planet_id:
                    print(name_planet)
                    full_download_link = urljoin(url, download_link)
                    print(full_download_link)
                    image_response = requests.get(full_download_link)
                    if image_response.status_code == 200:
                        return image_response
                    
print(fetch_textures_planets('mercury'))

mercury
https://www.solarsystemscope.com/textures/download/2k_mercury.jpg
<Response [200]>


In [24]:
import requests
from PIL import Image
from io import BytesIO
import numpy as np

image_urls = [
    "https://www.solarsystemscope.com/textures/download/2k_mercury.jpg",
    "https://www.solarsystemscope.com/textures/download/2k_venus_surface.jpg",
    # Agrega el resto de las URLs de las imágenes aquí
]

# Cargar la imagen desde el contenido de la respuesta
for image_url in image_urls:
    response = requests.get(image_url)
    if response.status_code == 200:
        image_content = BytesIO(response.content)
        image = Image.open(image_content)
        # Convertir la imagen a una matriz numpy
        image_array = np.array(image)
        # Ahora puedes trabajar con image_array
        print(f"Dimensiones de la imagen: {image_array.shape}")
        # Por ejemplo, imprimir los primeros 5 píxeles de la imagen
        print("Primeros 5 píxeles de la imagen:")
        print(image_array[:5])
    else:
        print(f"Fallo al descargar imagen desde {image_url}, estado: {response.status_code}")


Dimensiones de la imagen: (1024, 2048, 3)
Primeros 5 píxeles de la imagen:
[[[161 160 165]
  [159 158 163]
  [158 157 162]
  ...
  [162 161 166]
  [162 161 166]
  [162 161 166]]

 [[ 87  87  89]
  [ 87  87  89]
  [ 87  87  89]
  ...
  [ 86  85  90]
  [ 86  85  90]
  [ 86  85  90]]

 [[231 231 231]
  [231 231 231]
  [232 232 232]
  ...
  [232 232 234]
  [232 232 234]
  [232 232 234]]

 [[ 87  87  87]
  [ 86  86  86]
  [ 85  85  85]
  ...
  [ 84  84  84]
  [ 81  81  81]
  [ 79  79  79]]

 [[142 142 142]
  [142 142 142]
  [142 142 142]
  ...
  [131 131 131]
  [125 125 125]
  [120 120 120]]]
Dimensiones de la imagen: (1024, 2048, 3)
Primeros 5 píxeles de la imagen:
[[[204 116  42]
  [203 115  41]
  [202 114  40]
  ...
  [204 113  40]
  [204 113  40]
  [205 114  41]]

 [[203 112  39]
  [202 111  38]
  [201 110  37]
  ...
  [199 108  35]
  [200 109  36]
  [202 111  38]]

 [[202 111  38]
  [200 109  36]
  [199 108  35]
  ...
  [198 107  34]
  [197 109  35]
  [199 111  37]]

 [[201 111  35]
  